version: "3.3"
services:
  web:
    build: 
      context: website
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./website/:/usr/share/nginx/html/"
      - "./website/nginx-conf:/etc/nginx/conf.d"
  api:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - "./tmp/exported_model:/models/exported_model"
    environment:
      - MODEL_NAME=exported_model